#!/usr/bin/env bash
# GENERATED by bench/gen_campaign.py — campaign '27b-maxctx-f16'. Resumable: rerun to continue
# after an interruption (per-probe markers in <campaign>/done/). Edit the spec and
# regenerate, or hand-edit this file. Requires the servers' llama.cpp builds present.
#
# HAND-EDITED (2026-07-12): this is a max-context BRACKET campaign — servers at/above the VRAM
# ceiling are EXPECTED to OOM at start. A start failure is therefore recorded to failures.txt and
# the run CONTINUES to the next server (it does NOT exit), so the f16 OOM cannot halt the q8 arm.
# A failed server leaves its probe marker absent → it is re-attempted on the next resume (a
# deterministic OOM just re-fails cheaply and moves on).
set -uo pipefail
ROOT="${ROOT:-/home/dev/work/dp-craft/amd}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$ROOT/bench/runs/2026-07-12-27b-maxctx-f16}"
EB="$ROOT/bench/engine-bench"
GEN="$ROOT/bench/workloads/generated"
export MODEL='/home/dev/models/gguf/Qwen3.6-27B-Q4_K_S.gguf'
export ENGINES_LIST="llamacpp-vulkan|http://localhost:8081/v1|local"
mkdir -p "$CAMPAIGN_DIR/done"
if [ ! -f "$CAMPAIGN_DIR/meta.txt" ]; then
  { echo "date=$(date -Iseconds)"; echo "model=$MODEL"; echo "backend=vulkan"; echo "tuning=ub2048 b4096 faon"; } > "$CAMPAIGN_DIR/meta.txt"
fi

server_needed () {  # any listed probe marker missing?
  local s; for s in "$@"; do [ -f "$CAMPAIGN_DIR/done/$s" ] || return 0; done; return 1; }

stop_server () { PORT=8081 "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }

start_server () {  # name ctx kv  -> 0 if up, nonzero (recorded) if OOM/failed
  local name=$1 ctx=$2 kv=$3
  echo ">>> starting $name (ctx=$ctx kv=$kv)"
  if BACKEND=vulkan CTX="$ctx" NP=1 KV="$kv" MTP=0 UB=2048 B=4096 FA=on PORT=8081 \
       "$EB/serve_llamacpp.sh" start; then return 0; fi
  echo "SERVER-OOM/FAILED (expected bracket ceiling): $name ctx=$ctx kv=$kv" \
    | tee -a "$CAMPAIGN_DIR/failures.txt"
  stop_server; return 1; }

run_probe () {  # slug conc reps max_tokens api prefix prompt_files...
  local slug=$1 conc=$2 reps=$3 maxt=$4 api=$5 prefix=$6; shift 6
  if [ -f "$CAMPAIGN_DIR/done/$slug" ]; then echo "  skip (done): $slug"; return 0; fi
  local files=""; local f; for f in "$@"; do files="$files $GEN/$f"; done
  if PROMPT_FILE="$files" SLUG="$slug" MAX_TOKENS="$maxt" CONCURRENCY="$conc" \
       REPS="$reps" API="$api" PREFIX_MODE="$prefix" "$EB/run.sh"; then
    local rd; rd=$(ls -td "$ROOT"/bench/runs/*-engine-"$slug"/ 2>/dev/null | head -1)
    [ -n "$rd" ] && [ -f "$rd/results.jsonl" ] \
      && cat "$rd/results.jsonl" >> "$CAMPAIGN_DIR/results.jsonl"
    touch "$CAMPAIGN_DIR/done/$slug"
  else echo "  FAILED: $slug" | tee -a "$CAMPAIGN_DIR/failures.txt"; fi; }

trap stop_server EXIT

# ===== f16 arm — pin the f16 ceiling (expect PASS <=~56K, OOM by 64K) =====
if server_needed 'maxctx-f16-c48k'; then
  if start_server f16-c48k 49152 f16; then
    run_probe 'maxctx-f16-c48k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-f16-c56k'; then
  if start_server f16-c56k 57344 f16; then
    run_probe 'maxctx-f16-c56k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-f16-c60k'; then
  if start_server f16-c60k 61440 f16; then
    run_probe 'maxctx-f16-c60k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-f16-c64k'; then
  if start_server f16-c64k 65536 f16; then
    run_probe 'maxctx-f16-c64k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-f16-c100k'; then
  if start_server f16-c64k 100000 f16; then
    run_probe 'maxctx-f16-c64k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-f16-c200k'; then
  if start_server f16-c64k 200000 f16; then
    run_probe 'maxctx-f16-c64k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi

# ===== q8_0 arm — find the highest q8_0 context (expect PASS ~104K, OOM by 120K) =====
if server_needed 'maxctx-q8-c96k'; then
  if start_server q8-c96k 98304 q8_0; then
    run_probe 'maxctx-q8-c96k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi
if server_needed 'maxctx-q8-c200k'; then
  if start_server q8-c120k 200000 q8_0; then
    run_probe 'maxctx-q8-c120k' 1 2 256 completions unique 'codereview-40000.txt'; stop_server; fi
fi

# ===== report (last step) =====
if [ -f "$CAMPAIGN_DIR/results.jsonl" ]; then
  python3 "$ROOT/bench/lib/report.py" "$CAMPAIGN_DIR" \
    && echo "report: $CAMPAIGN_DIR/report.html"
fi
echo "campaign done. consolidated results: $CAMPAIGN_DIR/results.jsonl"
