#!/usr/bin/env bash
# GENERATED by bench/gen_campaign.py — campaign '27b-serving-substrate'. Resumable: rerun to continue
# after an interruption (per-probe markers in <campaign>/done/). Edit the spec and
# regenerate. Behaviour baked in (no hand-editing needed):
#   * CONTINUE-ON-FAILURE: a server that fails to start is recorded and the run moves on.
#   * PRE-FLIGHT VRAM GUARD: a server whose predicted VRAM > VRAM_BUDGET_MIB is SKIPPED
#     before launch → GPU/VRAM-only, never spills to system RAM (no GTT thrash / freeze).
#   * SUBSET / SHORT runs: ONLY='glob,..' picks probes; REPS=/MAX_TOKENS= shorten a pass.
#
# NOTE: Round-1 (quality-independent) substrate. Runs on the unsloth-MTP build because it uniquely carries the MTP axis; the prefill/KV/cache substrate is arch+quant-determined and transfers to jackrong (confirmed in Campaign 2 B0). All probes measure throughput/latency only (no judge). Depths 8/32/64K per user. Cache-reuse KV-shift variant + HIP spot-check are documented EXTRA_ARGS / BACKEND re-runs in the README (backend + server flags are global, not per-server).
set -uo pipefail
ROOT="${ROOT:-/home/dev/work/dp-craft/amd}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$ROOT/bench/runs/2026-07-12-27b-serving-substrate}"
EB="$ROOT/bench/engine-bench"
GEN="$ROOT/bench/workloads/generated"
export MODEL='/home/dev/models/gguf/Qwen3.6-27B-MTP-Q4_K_M.gguf'
export ENGINES_LIST="llamacpp-vulkan|http://localhost:8081/v1|local"
# --- run-time knobs (override on the command line) ---
VRAM_BUDGET_MIB="${VRAM_BUDGET_MIB:-32400}"  # guard: skip servers predicted above this
ONLY="${ONLY:-}"                 # comma-separated slug globs; empty = all probes
REPS_OVERRIDE="${REPS:-}"        # override every probe's reps (quick pass)
MAXTOK_OVERRIDE="${MAX_TOKENS:-}"  # override every probe's max_tokens
mkdir -p "$CAMPAIGN_DIR/done"
if [ ! -f "$CAMPAIGN_DIR/meta.txt" ]; then
  { echo "date=$(date -Iseconds)"; echo "model=$MODEL"; echo "backend=vulkan"; echo "tuning=ub2048 b4096 faon"; echo "vram_budget_mib=$VRAM_BUDGET_MIB"; } > "$CAMPAIGN_DIR/meta.txt"
fi

server_needed () {  # any listed probe marker missing?
  local s; for s in "$@"; do [ -f "$CAMPAIGN_DIR/done/$s" ] || return 0; done; return 1; }

want_probe () {  # honor ONLY='glob,glob' filter
  [ -z "$ONLY" ] && return 0
  local g; IFS="," read -ra _globs <<<"$ONLY"
  for g in "${_globs[@]}"; do case "$1" in $g) return 0;; esac; done; return 1; }

probes_selected () {  # 0 if ONLY matches >=1 of this server's probes (don't load a model
  local s; for s in "$@"; do want_probe "$s" && return 0; done; return 1; }  # for filtered-out probes

guard_ok () {  # name predicted_mib -> 0 if within budget (or unknown), else record SKIPPED
  local name=$1 pred=$2
  [ "$pred" -lt 0 ] && return 0   # no prediction available (spec has no vram block)
  if [ "$pred" -gt "$VRAM_BUDGET_MIB" ]; then
    echo "SKIPPED (predicted ${pred} MiB > budget ${VRAM_BUDGET_MIB} MiB): $name" \
      | tee -a "$CAMPAIGN_DIR/skipped.txt"; return 1; fi
  return 0; }

ensure_fixtures () {  # auto-build any missing prompt fixture from its canonical recipe
  local WL="$ROOT/bench/workloads" name n k
  for name in "$@"; do
    [ -f "$GEN/$name" ] && continue
    echo ">>> building missing fixture: $name"
    case "$name" in
      codereview-*.txt)
        n="${name#codereview-}"; n="${n%.txt}"
        python3 "$WL/build_prompt.py" --task "$WL/tasks/codereview-large.task.md" \
          --src "$WL/corpus/ts-agentic-code-runner" --src "$WL/corpus/py-rich" \
          --target-tokens "$n" --out "$GEN/$name" ;;
      thinking-hard.txt)
        python3 "$WL/build_prompt.py" --task "$WL/tasks/thinking-hard.prompt.txt" \
          --target-tokens 0 --out "$GEN/thinking-hard.txt" ;;
      agentic-*-v*.txt)  # variant set: build the base with enough --variants (writes v1..vK)
        n="${name#agentic-}"; n="${n%%-v*}"; k="${name##*-v}"; k="${k%.txt}"
        python3 "$WL/build_prompt.py" --task "$WL/tasks/agentic-implement.task.md" \
          --src "$WL/corpus/ts-agentic-code-runner" --target-tokens "$n" \
          --variants "$k" --out "$GEN/agentic-$n.txt" ;;
      agentic-*.txt)
        n="${name#agentic-}"; n="${n%.txt}"
        python3 "$WL/build_prompt.py" --task "$WL/tasks/agentic-implement.task.md" \
          --src "$WL/corpus/ts-agentic-code-runner" --target-tokens "$n" --out "$GEN/$name" ;;
      *)
        echo "FIXTURE-UNKNOWN: no build recipe for '$name' — build it by hand (see" \
             "bench/workloads/README.md) and re-run" >&2; exit 1 ;;
    esac
    [ -f "$GEN/$name" ] || { echo "FIXTURE-BUILD-FAILED: $name" >&2; exit 1; }
  done; }

run_probe () {  # slug conc reps max_tokens api prefix prompt_files...
  local slug=$1 conc=$2 reps=$3 maxt=$4 api=$5 prefix=$6; shift 6
  if [ -f "$CAMPAIGN_DIR/done/$slug" ]; then echo "  skip (done): $slug"; return 0; fi
  if ! want_probe "$slug"; then echo "  skip (ONLY filter): $slug"; return 0; fi
  [ -n "$REPS_OVERRIDE" ] && reps="$REPS_OVERRIDE"
  [ -n "$MAXTOK_OVERRIDE" ] && maxt="$MAXTOK_OVERRIDE"
  local files=""; local f; for f in "$@"; do files="$files $GEN/$f"; done
  if PROMPT_FILE="$files" SLUG="$slug" MAX_TOKENS="$maxt" CONCURRENCY="$conc" \
       REPS="$reps" API="$api" PREFIX_MODE="$prefix" SAMPLE_VRAM=1 "$EB/run.sh"; then
    local rd; rd=$(ls -td "$ROOT"/bench/runs/*-engine-"$slug"/ 2>/dev/null | head -1)
    [ -n "$rd" ] && [ -f "$rd/results.jsonl" ] \
      && cat "$rd/results.jsonl" >> "$CAMPAIGN_DIR/results.jsonl"
    touch "$CAMPAIGN_DIR/done/$slug"
  else echo "  FAILED: $slug" | tee -a "$CAMPAIGN_DIR/failures.txt"; fi; }

stop_server () { PORT=8081 "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }
start_server () {  # name ctx kv -> 0 up, nonzero (recorded) on failure; run CONTINUES
  local name=$1 ctx=$2 kv=$3 mtp=$4 np=$5
  echo ">>> starting $name (ctx=$ctx kv=$kv mtp=$mtp np=$np)"
  if BACKEND=vulkan CTX="$ctx" NP="$np" KV="$kv" MTP="$mtp" UB=2048 B=4096 FA=on PORT=8081 \
       "$EB/serve_llamacpp.sh" start; then return 0; fi
  echo "SERVER-FAILED (start OOM/other; expected near the ceiling): $name ctx=$ctx kv=$kv" \
    | tee -a "$CAMPAIGN_DIR/failures.txt"; stop_server; return 1; }
trap stop_server EXIT

# --- pre-flight: build any missing prompt fixtures before loading a model ---
ensure_fixtures 'codereview-32000.txt' 'codereview-64000.txt' 'codereview-8000.txt' 'thinking-hard.txt'

# ===== server: sub-f16 (ctx=65536 np=1 kv=f16 mtp=0 predicted_vram=22408 MiB) =====
if ! server_needed 'pf-cr8000' 'pf-cr32000' 'pf-cr64000' 'warm-cr32000' 'dec-think'; then
  echo "  skip (done): sub-f16 — all its probes are already complete"
elif ! probes_selected 'pf-cr8000' 'pf-cr32000' 'pf-cr64000' 'warm-cr32000' 'dec-think'; then
  echo "  skip (ONLY filter): sub-f16"
elif guard_ok 'sub-f16' 22408; then
  if start_server 'sub-f16' 65536 'f16' 0 1; then
    run_probe 'pf-cr8000' 1 3 256 completions unique 'codereview-8000.txt'
    run_probe 'pf-cr32000' 1 3 256 completions unique 'codereview-32000.txt'
    run_probe 'pf-cr64000' 1 3 256 completions unique 'codereview-64000.txt'
    run_probe 'warm-cr32000' 1 4 256 completions shared 'codereview-32000.txt'
    run_probe 'dec-think' 1 3 512 chat unique 'thinking-hard.txt'
    stop_server
  fi
fi

# ===== server: sub-q8 (ctx=65536 np=1 kv=q8_0 mtp=0 predicted_vram=20488 MiB) =====
if ! server_needed 'pf-cr32000-q8' 'pf-cr64000-q8' 'dec-think-q8'; then
  echo "  skip (done): sub-q8 — all its probes are already complete"
elif ! probes_selected 'pf-cr32000-q8' 'pf-cr64000-q8' 'dec-think-q8'; then
  echo "  skip (ONLY filter): sub-q8"
elif guard_ok 'sub-q8' 20488; then
  if start_server 'sub-q8' 65536 'q8_0' 0 1; then
    run_probe 'pf-cr32000-q8' 1 3 256 completions unique 'codereview-32000.txt'
    run_probe 'pf-cr64000-q8' 1 3 256 completions unique 'codereview-64000.txt'
    run_probe 'dec-think-q8' 1 3 512 chat unique 'thinking-hard.txt'
    stop_server
  fi
fi

# ===== server: sub-mtp1 (ctx=65536 np=1 kv=f16 mtp=1 predicted_vram=22408 MiB) =====
if ! server_needed 'pf-cr32000-mtp1' 'dec-think-mtp1'; then
  echo "  skip (done): sub-mtp1 — all its probes are already complete"
elif ! probes_selected 'pf-cr32000-mtp1' 'dec-think-mtp1'; then
  echo "  skip (ONLY filter): sub-mtp1"
elif guard_ok 'sub-mtp1' 22408; then
  if start_server 'sub-mtp1' 65536 'f16' 1 1; then
    run_probe 'pf-cr32000-mtp1' 1 3 256 completions unique 'codereview-32000.txt'
    run_probe 'dec-think-mtp1' 1 3 512 chat unique 'thinking-hard.txt'
    stop_server
  fi
fi

# ===== report (last step) =====
if [ -f "$CAMPAIGN_DIR/results.jsonl" ]; then
  python3 "$ROOT/bench/lib/report.py" "$CAMPAIGN_DIR" \
    && echo "report: $CAMPAIGN_DIR/report.html"
fi
echo "campaign done. consolidated results: $CAMPAIGN_DIR/results.jsonl"
[ -f "$CAMPAIGN_DIR/skipped.txt" ] && { echo "--- guard-skipped (over budget) ---"; cat "$CAMPAIGN_DIR/skipped.txt"; } || true
