#!/usr/bin/env bash
# GENERATED by bench/gen_campaign.py — campaign '27b-maxctx-v2'. Resumable: rerun to continue
# after an interruption (per-probe markers in <campaign>/done/). Edit the spec and
# regenerate. Behaviour baked in (no hand-editing needed):
#   * CONTINUE-ON-FAILURE: a server that fails to start is recorded and the run moves on.
#   * PRE-FLIGHT VRAM GUARD: a server whose predicted VRAM > VRAM_BUDGET_MIB is SKIPPED
#     before launch → GPU/VRAM-only, never spills to system RAM (no GTT thrash / freeze).
#   * SUBSET / SHORT runs: ONLY='glob,..' picks probes; REPS=/MAX_TOKENS= shorten a pass.
#
# NOTE: *** CORRECTED 2026-07-12 — the original premise of this campaign was WRONG. ***
# NOTE: Qwen3.6-27B is a HYBRID arch (qwen35): 65 blocks, but only 16 are full-attention; 48 are
# NOTE: SSM/Gated-DeltaNet linear-attention (fixed state, NO growing KV) + 1 nextn/MTP. Only the 16
# NOTE: attention layers cache KV. => f16 KV = 16*4*(256+256)*2B = 64 KiB/token; q8_0 ~= 34 KiB/token.
# NOTE: (The earlier 260/138 numbers wrongly multiplied by all 65 blocks.) So f16 fits to ~240K and
# NOTE: q8_0 to the full native 262K in 32 GB. MEASURED: 200K f16 loaded in 31s using 29.0 GiB VRAM.
# NOTE: The old 'max-limit' 200K/230K servers below now FIT and will actually run (not guard-skip).
# NOTE: This campaign is effectively superseded — see docs/plans/2026-07-12-27b-finetune-quality-tokens.md
# NOTE: and the corrected bench/gguf_kv.py (hybrid-aware). Kept for the audit trail of the correction.
set -uo pipefail
ROOT="${ROOT:-/home/dev/work/dp-craft/amd}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$ROOT/bench/runs/2026-07-12-27b-maxctx-v2}"
EB="$ROOT/bench/engine-bench"
GEN="$ROOT/bench/workloads/generated"
export MODEL='/home/dev/models/gguf/Qwen3.6-27B-Q4_K_S.gguf'
export ENGINES_LIST="llamacpp-vulkan|http://localhost:8081/v1|local"
# --- run-time knobs (override on the command line) ---
VRAM_BUDGET_MIB="${VRAM_BUDGET_MIB:-32400}"  # guard: skip servers predicted above this
ONLY="${ONLY:-}"                 # comma-separated slug globs; empty = all probes
REPS_OVERRIDE="${REPS:-}"        # override every probe's reps (quick pass)
MAXTOK_OVERRIDE="${MAX_TOKENS:-}"  # override every probe's max_tokens
mkdir -p "$CAMPAIGN_DIR/done"
if [ ! -f "$CAMPAIGN_DIR/meta.txt" ]; then
  { echo "date=$(date -Iseconds)"; echo "model=$MODEL"; echo "backend=vulkan"; echo "tuning=ub2048 b4096 faon"; echo "vram_budget_mib=$VRAM_BUDGET_MIB"; } > "$CAMPAIGN_DIR/meta.txt"
fi

server_needed () {  # any listed probe marker missing?
  local s; for s in "$@"; do [ -f "$CAMPAIGN_DIR/done/$s" ] || return 0; done; return 1; }

want_probe () {  # honor ONLY='glob,glob' filter
  [ -z "$ONLY" ] && return 0
  local g; IFS="," read -ra _globs <<<"$ONLY"
  for g in "${_globs[@]}"; do case "$1" in $g) return 0;; esac; done; return 1; }

probes_selected () {  # 0 if ONLY matches >=1 of this server's probes (don't load a model
  local s; for s in "$@"; do want_probe "$s" && return 0; done; return 1; }  # for filtered-out probes

guard_ok () {  # name predicted_mib -> 0 if within budget (or unknown), else record SKIPPED
  local name=$1 pred=$2
  [ "$pred" -lt 0 ] && return 0   # no prediction available (spec has no vram block)
  if [ "$pred" -gt "$VRAM_BUDGET_MIB" ]; then
    echo "SKIPPED (predicted ${pred} MiB > budget ${VRAM_BUDGET_MIB} MiB): $name" \
      | tee -a "$CAMPAIGN_DIR/skipped.txt"; return 1; fi
  return 0; }

run_probe () {  # slug conc reps max_tokens api prefix prompt_files...
  local slug=$1 conc=$2 reps=$3 maxt=$4 api=$5 prefix=$6; shift 6
  if [ -f "$CAMPAIGN_DIR/done/$slug" ]; then echo "  skip (done): $slug"; return 0; fi
  if ! want_probe "$slug"; then echo "  skip (ONLY filter): $slug"; return 0; fi
  [ -n "$REPS_OVERRIDE" ] && reps="$REPS_OVERRIDE"
  [ -n "$MAXTOK_OVERRIDE" ] && maxt="$MAXTOK_OVERRIDE"
  local files=""; local f; for f in "$@"; do files="$files $GEN/$f"; done
  if PROMPT_FILE="$files" SLUG="$slug" MAX_TOKENS="$maxt" CONCURRENCY="$conc" \
       REPS="$reps" API="$api" PREFIX_MODE="$prefix" SAMPLE_VRAM=1 "$EB/run.sh"; then
    local rd; rd=$(ls -td "$ROOT"/bench/runs/*-engine-"$slug"/ 2>/dev/null | head -1)
    [ -n "$rd" ] && [ -f "$rd/results.jsonl" ] \
      && cat "$rd/results.jsonl" >> "$CAMPAIGN_DIR/results.jsonl"
    touch "$CAMPAIGN_DIR/done/$slug"
  else echo "  FAILED: $slug" | tee -a "$CAMPAIGN_DIR/failures.txt"; fi; }

stop_server () { PORT=8081 "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }
start_server () {  # name ctx kv -> 0 up, nonzero (recorded) on failure; run CONTINUES
  local name=$1 ctx=$2 kv=$3 mtp=$4 np=$5
  echo ">>> starting $name (ctx=$ctx kv=$kv mtp=$mtp np=$np)"
  if BACKEND=vulkan CTX="$ctx" NP="$np" KV="$kv" MTP="$mtp" UB=2048 B=4096 FA=on PORT=8081 \
       "$EB/serve_llamacpp.sh" start; then return 0; fi
  echo "SERVER-FAILED (start OOM/other; expected near the ceiling): $name ctx=$ctx kv=$kv" \
    | tee -a "$CAMPAIGN_DIR/failures.txt"; stop_server; return 1; }
trap stop_server EXIT

# ===== server: f16-c32k (ctx=32768 np=1 kv=f16 mtp=0 predicted_vram=19418 MiB) =====
if ! server_needed 'mc-f16-c32k'; then
  echo "  skip (done): f16-c32k — all its probes are already complete"
elif ! probes_selected 'mc-f16-c32k'; then
  echo "  skip (ONLY filter): f16-c32k"
elif guard_ok 'f16-c32k' 19418; then
  if start_server 'f16-c32k' 32768 'f16' 0 1; then
    run_probe 'mc-f16-c32k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c48k (ctx=49152 np=1 kv=f16 mtp=0 predicted_vram=20442 MiB) =====
if ! server_needed 'mc-f16-c48k'; then
  echo "  skip (done): f16-c48k — all its probes are already complete"
elif ! probes_selected 'mc-f16-c48k'; then
  echo "  skip (ONLY filter): f16-c48k"
elif guard_ok 'f16-c48k' 20442; then
  if start_server 'f16-c48k' 49152 'f16' 0 1; then
    run_probe 'mc-f16-c48k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c56k (ctx=57344 np=1 kv=f16 mtp=0 predicted_vram=20954 MiB) =====
if ! server_needed 'mc-f16-c56k'; then
  echo "  skip (done): f16-c56k — all its probes are already complete"
elif ! probes_selected 'mc-f16-c56k'; then
  echo "  skip (ONLY filter): f16-c56k"
elif guard_ok 'f16-c56k' 20954; then
  if start_server 'f16-c56k' 57344 'f16' 0 1; then
    run_probe 'mc-f16-c56k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c60k (ctx=61440 np=1 kv=f16 mtp=0 predicted_vram=21210 MiB) =====
if ! server_needed 'mc-f16-c60k'; then
  echo "  skip (done): f16-c60k — all its probes are already complete"
elif ! probes_selected 'mc-f16-c60k'; then
  echo "  skip (ONLY filter): f16-c60k"
elif guard_ok 'f16-c60k' 21210; then
  if start_server 'f16-c60k' 61440 'f16' 0 1; then
    run_probe 'mc-f16-c60k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c64k (ctx=65536 np=1 kv=q8_0 mtp=0 predicted_vram=19546 MiB) =====
if ! server_needed 'mc-q8-c64k'; then
  echo "  skip (done): q8-c64k — all its probes are already complete"
elif ! probes_selected 'mc-q8-c64k'; then
  echo "  skip (ONLY filter): q8-c64k"
elif guard_ok 'q8-c64k' 19546; then
  if start_server 'q8-c64k' 65536 'q8_0' 0 1; then
    run_probe 'mc-q8-c64k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c96k (ctx=98304 np=1 kv=q8_0 mtp=0 predicted_vram=20634 MiB) =====
if ! server_needed 'mc-q8-c96k'; then
  echo "  skip (done): q8-c96k — all its probes are already complete"
elif ! probes_selected 'mc-q8-c96k'; then
  echo "  skip (ONLY filter): q8-c96k"
elif guard_ok 'q8-c96k' 20634; then
  if start_server 'q8-c96k' 98304 'q8_0' 0 1; then
    run_probe 'mc-q8-c96k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c112k (ctx=114688 np=1 kv=q8_0 mtp=0 predicted_vram=21178 MiB) =====
if ! server_needed 'mc-q8-c112k'; then
  echo "  skip (done): q8-c112k — all its probes are already complete"
elif ! probes_selected 'mc-q8-c112k'; then
  echo "  skip (ONLY filter): q8-c112k"
elif guard_ok 'q8-c112k' 21178; then
  if start_server 'q8-c112k' 114688 'q8_0' 0 1; then
    run_probe 'mc-q8-c112k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c116k (ctx=118784 np=1 kv=q8_0 mtp=0 predicted_vram=21314 MiB) =====
if ! server_needed 'mc-q8-c116k'; then
  echo "  skip (done): q8-c116k — all its probes are already complete"
elif ! probes_selected 'mc-q8-c116k'; then
  echo "  skip (ONLY filter): q8-c116k"
elif guard_ok 'q8-c116k' 21314; then
  if start_server 'q8-c116k' 118784 'q8_0' 0 1; then
    run_probe 'mc-q8-c116k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c64k-edge (ctx=65536 np=1 kv=f16 mtp=0 predicted_vram=21466 MiB) =====
if ! server_needed 'mc-f16-c64k'; then
  echo "  skip (done): f16-c64k-edge — all its probes are already complete"
elif ! probes_selected 'mc-f16-c64k'; then
  echo "  skip (ONLY filter): f16-c64k-edge"
elif guard_ok 'f16-c64k-edge' 21466; then
  if start_server 'f16-c64k-edge' 65536 'f16' 0 1; then
    run_probe 'mc-f16-c64k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c120k-edge (ctx=122880 np=1 kv=q8_0 mtp=0 predicted_vram=21450 MiB) =====
if ! server_needed 'mc-q8-c120k'; then
  echo "  skip (done): q8-c120k-edge — all its probes are already complete"
elif ! probes_selected 'mc-q8-c120k'; then
  echo "  skip (ONLY filter): q8-c120k-edge"
elif guard_ok 'q8-c120k-edge' 21450; then
  if start_server 'q8-c120k-edge' 122880 'q8_0' 0 1; then
    run_probe 'mc-q8-c120k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c200k-max (ctx=204800 np=1 kv=f16 mtp=0 predicted_vram=30170 MiB) =====
if ! server_needed 'mc-f16-c200k'; then
  echo "  skip (done): f16-c200k-max — all its probes are already complete"
elif ! probes_selected 'mc-f16-c200k'; then
  echo "  skip (ONLY filter): f16-c200k-max"
elif guard_ok 'f16-c200k-max' 30170; then
  if start_server 'f16-c200k-max' 204800 'f16' 0 1; then
    run_probe 'mc-f16-c200k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: f16-c230k-max (ctx=235520 np=1 kv=f16 mtp=0 predicted_vram=32090 MiB) =====
if ! server_needed 'mc-f16-c230k'; then
  echo "  skip (done): f16-c230k-max — all its probes are already complete"
elif ! probes_selected 'mc-f16-c230k'; then
  echo "  skip (ONLY filter): f16-c230k-max"
elif guard_ok 'f16-c230k-max' 32090; then
  if start_server 'f16-c230k-max' 235520 'f16' 0 1; then
    run_probe 'mc-f16-c230k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c200k-max (ctx=204800 np=1 kv=q8_0 mtp=0 predicted_vram=24170 MiB) =====
if ! server_needed 'mc-q8-c200k'; then
  echo "  skip (done): q8-c200k-max — all its probes are already complete"
elif ! probes_selected 'mc-q8-c200k'; then
  echo "  skip (ONLY filter): q8-c200k-max"
elif guard_ok 'q8-c200k-max' 24170; then
  if start_server 'q8-c200k-max' 204800 'q8_0' 0 1; then
    run_probe 'mc-q8-c200k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== server: q8-c230k-max (ctx=235520 np=1 kv=q8_0 mtp=0 predicted_vram=25190 MiB) =====
if ! server_needed 'mc-q8-c230k'; then
  echo "  skip (done): q8-c230k-max — all its probes are already complete"
elif ! probes_selected 'mc-q8-c230k'; then
  echo "  skip (ONLY filter): q8-c230k-max"
elif guard_ok 'q8-c230k-max' 25190; then
  if start_server 'q8-c230k-max' 235520 'q8_0' 0 1; then
    run_probe 'mc-q8-c230k' 1 2 256 completions unique 'codereview-8000.txt'
    stop_server
  fi
fi

# ===== report (last step) =====
if [ -f "$CAMPAIGN_DIR/results.jsonl" ]; then
  python3 "$ROOT/bench/lib/report.py" "$CAMPAIGN_DIR" \
    && echo "report: $CAMPAIGN_DIR/report.html"
fi
echo "campaign done. consolidated results: $CAMPAIGN_DIR/results.jsonl"
[ -f "$CAMPAIGN_DIR/skipped.txt" ] && { echo "--- guard-skipped (over budget) ---"; cat "$CAMPAIGN_DIR/skipped.txt"; } || true
