#!/usr/bin/env bash
# GENERATED by bench/gen_campaign.py — QUALITY campaign '27b-finetune-quality'. Resumable: rerun to
# continue (per-config markers in out/done/). Edit the spec and regenerate. Behaviour:
#   * Per config: serve ONE llama-server → sample VRAM/GTT/power → capture the task suite
#     (capture_engine tasks: full telemetry, saved responses) → stop. Then deterministic
#     scoring + SVG report. CONTINUE-ON-FAIL; PRE-FLIGHT VRAM GUARD skips a model predicted
#     over budget (VRAM-only, no GTT spill/freeze).
#   * Subset / short pass: ONLY='glob' picks configs; REPS=/MAX_TOKENS= shorten a run.
# NOTE: All 5 configs share the identical qwen35 HYBRID arch (16 full-attn + 48 SSM + 1 nextn),
# NOTE: so KV geometry (f16 64 KiB/tok) and max-context are identical -> the comparison is quality
# NOTE: + token economy, NOT context. ctx 32768 is far above task need and keeps VRAM comparable.
set -uo pipefail
ROOT="${ROOT:-/home/dev/work/dp-craft/amd/.claude/worktrees/unify-harness}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$ROOT/campaigns/2026-07-12-27b-finetune-quality}"
LIB="$ROOT/bench/lib"; EB="$ROOT/bench/engine-bench"
OUT="$CAMPAIGN_DIR/out"; mkdir -p "$OUT/done"
OUTF="$OUT/outputs.jsonl"; VRAMF="$OUT/vram.jsonl"
MODELS_DIR="${MODELS_DIR:-/home/dev/models/gguf}"
TASKS="${TASKS:-$CAMPAIGN_DIR/tasks/tasks.jsonl}"
BACKEND='vulkan'; PORT=8081; CTX=32768; KV='f16'; UB=2048; B=4096; FA='on'
REPS="${REPS:-1}"; MAX_TOKENS="${MAX_TOKENS:-8192}"; API='chat'
VRAM_BUDGET_MIB="${VRAM_BUDGET_MIB:-32400}"; OVERHEAD_MIB=2000; KV_KIB_PER_TOK=64  # 0 = guard off
ONLY="${ONLY:-}"                 # space/comma glob(s) on config label; empty = all

# config triples: label | model filename (under MODELS_DIR) | mtp(0|1)
CONFIGS=(
  'rico03-distilled|Qwen3.6-27B-Claude-Opus-Reasoning-Distilled-Q4_K_S.gguf|0'
  'unsloth-mtp-off|Qwen3.6-27B-MTP-Q4_K_M.gguf|0'
  'unsloth-mtp-on|Qwen3.6-27B-MTP-Q4_K_M.gguf|1'
  'hauhau-uncensored|Qwen3.6-27B-Uncensored-HauhauCS-Aggressive-IQ4_XS.gguf|0'
  'jackrong-qwopus|Qwopus3.6-27B-v1-preview-Q4_K_M.gguf|0'
)

vram_used_mib(){ rocm-smi --showmeminfo vram 2>/dev/null | awk -F: '/VRAM Total Used/{gsub(/ /,"",$NF); printf "%d",$NF/1048576}'; }
want(){ [ -z "$ONLY" ] && return 0; local g; for g in ${ONLY//,/ }; do case "$1" in $g) return 0;; esac; done; return 1; }
guard_ok(){  # $1=model path -> 0 ok/unknown, 1 skip (recorded)
  [ "$KV_KIB_PER_TOK" -le 0 ] && return 0
  local wmib=$(( $(stat -c%s "$1" 2>/dev/null || echo 0) / 1048576 ))
  [ "$wmib" -le 0 ] && return 0
  local pred=$(( wmib + OVERHEAD_MIB + KV_KIB_PER_TOK * CTX / 1024 ))
  if [ "$pred" -gt "$VRAM_BUDGET_MIB" ]; then
    echo "  SKIPPED (predicted ${pred} MiB > budget ${VRAM_BUDGET_MIB} MiB): $(basename "$1")" \
      | tee -a "$CAMPAIGN_DIR/skipped.txt"; return 1; fi
  echo "  VRAM predicted ${pred} MiB (budget ${VRAM_BUDGET_MIB})"; return 0; }
stop_server(){ PORT=8081 bash "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }
trap stop_server EXIT

for entry in "${CONFIGS[@]}"; do
  IFS="|" read -r label file mtp <<< "$entry"
  want "$label" || { echo "skip (ONLY): $label"; continue; }
  [ -f "$OUT/done/$label" ] && { echo "skip (done): $label"; continue; }
  model="$MODELS_DIR/$file"
  [ -f "$model" ] || { echo "MISSING MODEL: $model" | tee -a "$CAMPAIGN_DIR/failures.txt"; continue; }
  echo "=== $label  (mtp=$mtp)  $file ==="
  guard_ok "$model" || continue
  t0=$(date +%s)
  if MODEL="$model" BACKEND="$BACKEND" PORT="$PORT" CTX="$CTX" NP=1 UB="$UB" B="$B" FA="$FA" \
       KV="$KV" MTP="$mtp" bash "$EB/serve_llamacpp.sh" start; then
    load_s=$(( $(date +%s) - t0 )); used=$(vram_used_mib)
    echo "  VRAM at load: ${used} MiB  (load ${load_s}s)"
    curl -s -m 10 "http://127.0.0.1:$PORT/props" > "$OUT/props_${label}.json" 2>/dev/null || true
    msize=$(stat -c%s "$model" 2>/dev/null || echo 0)
    csv="$OUT/gpu_${label}.csv"; SPID=""
    if command -v rocm-smi >/dev/null 2>&1 || command -v nvidia-smi >/dev/null 2>&1; then
      python3 "$LIB/vram_sampler.py" --out "$csv" --interval 1 & SPID=$!
      for _ in 1 2 3 4; do [ -s "$csv" ] && [ "$(wc -l <"$csv")" -ge 2 ] && break
        kill -0 "$SPID" 2>/dev/null || break; sleep 0.5; done
    fi
    python3 "$LIB/capture_engine.py" tasks --url "http://127.0.0.1:$PORT/v1" --config "$label" \
       --tasks "$TASKS" --out "$OUTF" --reps "$REPS" --max-tokens "$MAX_TOKENS" --api "$API" \
       && touch "$OUT/done/$label"
    [ -n "$SPID" ] && { kill "$SPID" 2>/dev/null; wait "$SPID" 2>/dev/null || true; }
    python3 - "$label" "$file" "$mtp" "$CTX" "$KV" "$used" "$csv" "$load_s" "$msize" >> "$VRAMF" <<'PY'
import sys, json, re
label, file, mtp, ctx, kv, used, csv, load_s, msize = sys.argv[1:10]
row = {"config": label, "file": file, "mtp": int(mtp), "ctx": int(ctx), "kv": kv,
       "vram_used_mib_at_load": int(used), "load_time_s": int(load_s),
       "model_size_bytes": int(msize), "weights_gib": round(int(msize) / 2**30, 2)}
try:
    summ = [l for l in open(csv) if l.startswith("#")][-1]
    for k, val in re.findall(r"(\w+)=([\d.]+)", summ):
        row[k] = float(val) if "." in val else int(val)
except Exception as e:
    row["sampler_note"] = str(e)
print(json.dumps(row))
PY
  else
    echo "SERVER FAILED to start: $label" | tee -a "$CAMPAIGN_DIR/failures.txt"
  fi
  stop_server; sleep 2
done

echo; echo "=== deterministic scoring ==="
python3 "$ROOT/bench/lib/graders/score_deterministic.py" --tasks "$TASKS" \
  --outputs "$OUTF" --out "$OUT/scores_deterministic.jsonl" || true
echo; echo "=== charts + appendix (SVG, embedded in analysis.md) ==="
python3 "$LIB/report.py" "$CAMPAIGN_DIR" || true
echo; echo "Phase A complete. Raw telemetry: $OUTF ; per-config VRAM/power: $VRAMF"
echo "Next: Phase B (LLM-judge, see plan.md) → Phase C (write analysis.md)."
[ -f "$CAMPAIGN_DIR/skipped.txt" ] && { echo "--- guard-skipped ---"; cat "$CAMPAIGN_DIR/skipped.txt"; } || true
