#!/usr/bin/env python3
"""Deterministic campaign scaffolder for the R9700 benchmark harness.

Turns a small JSON *spec* (which servers to launch, which probes to run against each)
into a **resumable** `run.sh` plus a README skeleton under
`docs/campaigns/<date>-<slug>/`. The judgement (which depths, MTP/KV matrix, VRAM budget)
is expected to come from the `/new-campaign` skill or from you; this tool only emits the
mechanical, reproducible driver. It is safe to run by hand — see `--help` and the example.

Subcommands
-----------
  emit --spec SPEC.json [--force] [--print]
        Generate docs/campaigns/<date>-<slug>/{run.sh,README.md}. run.sh is always
        (re)written; README.md is written only if absent (never clobbers a hand-written one).
  vram-ctx --weights-gib G --kv-kib-per-tok K --budget-mib M [--np N]
        Deterministic VRAM→max-context helper (the math behind the deep-context campaign).
  example
        Print a minimal example spec to stdout.

Spec schema (JSON)
------------------
{
  "slug": "deep-context",             # required; campaign dir = <date>-<slug>
  "date": "2026-07-11",               # optional (default: today)
  "title": "Deep-context campaign",   # optional (README H1)
  "model": "/abs/path/model.gguf",    # required
  "backend": "vulkan",                # rocm|vulkan  (engine URL/port wiring)
  "port": 8081,                       # server port (must match backend's engine URL)
  "tuning": {"ub": 2048, "b": 4096, "fa": "on"},
  "servers": [
    {"name": "single-mtp0", "ctx": 262144, "np": 1, "kv": "f16", "mtp": 0,
     "probes": [
       {"slug": "deep-mtp0-cr8000", "prompts": ["codereview-8000.txt"],
        "max_tokens": 256, "api": "completions", "concurrency": 1, "reps": 2,
        "prefix_mode": "unique"}
     ]}
  ]
}
Probe defaults: max_tokens 256, api "completions", concurrency 1, reps 2, prefix_mode "unique".
Each probe SLUG must be unique in the campaign (the driver globs its run dir by that slug).
"""
import sys, os, json, argparse, datetime, stat

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND_PORT = {"rocm": 8080, "vulkan": 8081}


def sh_quote(s):
    return "'" + str(s).replace("'", "'\\''") + "'"


def emit_runsh(spec):
    slug = spec["slug"]
    date = spec.get("date") or datetime.date.today().isoformat()
    backend = spec.get("backend", "vulkan")
    port = spec.get("port") or BACKEND_PORT.get(backend, 8080)
    tune = spec.get("tuning", {})
    ub, b, fa = tune.get("ub", 2048), tune.get("b", 4096), tune.get("fa", "on")
    engine_name = f"llamacpp-{backend}" if backend in BACKEND_PORT else backend

    L = []
    ad = L.append
    ad("#!/usr/bin/env bash")
    ad(f"# GENERATED by bench/gen_campaign.py — campaign '{slug}'. Resumable: rerun to continue")
    ad("# after an interruption (per-probe markers in <campaign>/done/). Edit the spec and")
    ad("# regenerate, or hand-edit this file. Requires the servers' llama.cpp builds present.")
    ad("set -uo pipefail")
    ad('ROOT="${ROOT:-' + REPO + '}"')
    ad(f'CAMPAIGN_DIR="${{CAMPAIGN_DIR:-$ROOT/bench/runs/{date}-{slug}}}"')
    ad('EB="$ROOT/bench/engine-bench"')
    ad('GEN="$ROOT/bench/workloads/generated"')
    ad(f'export MODEL={sh_quote(spec["model"])}')
    ad(f'export ENGINES_LIST="{engine_name}|http://localhost:{port}/v1|local"')
    ad('mkdir -p "$CAMPAIGN_DIR/done"')
    ad('if [ ! -f "$CAMPAIGN_DIR/meta.txt" ]; then')
    ad('  { echo "date=$(date -Iseconds)"; echo "model=$MODEL"; '
       f'echo "backend={backend}"; echo "tuning=ub{ub} b{b} fa{fa}"; }} > "$CAMPAIGN_DIR/meta.txt"')
    ad('fi')
    ad("")
    ad("server_needed () {  # any listed probe marker missing?")
    ad('  local s; for s in "$@"; do [ -f "$CAMPAIGN_DIR/done/$s" ] || return 0; done; return 1; }')
    ad("")
    ad("run_probe () {  # slug conc reps max_tokens api prefix prompt_files...")
    ad("  local slug=$1 conc=$2 reps=$3 maxt=$4 api=$5 prefix=$6; shift 6")
    ad('  if [ -f "$CAMPAIGN_DIR/done/$slug" ]; then echo "  skip (done): $slug"; return 0; fi')
    ad('  local files=""; local f; for f in "$@"; do files="$files $GEN/$f"; done')
    ad('  if PROMPT_FILE="$files" SLUG="$slug" MAX_TOKENS="$maxt" CONCURRENCY="$conc" \\')
    ad('       REPS="$reps" API="$api" PREFIX_MODE="$prefix" "$EB/run.sh"; then')
    ad('    local rd; rd=$(ls -td "$ROOT"/bench/runs/*-engine-"$slug"/ 2>/dev/null | head -1)')
    ad('    [ -n "$rd" ] && [ -f "$rd/results.jsonl" ] \\')
    ad('      && cat "$rd/results.jsonl" >> "$CAMPAIGN_DIR/results.jsonl"')
    ad('    touch "$CAMPAIGN_DIR/done/$slug"')
    ad('  else echo "  FAILED: $slug" | tee -a "$CAMPAIGN_DIR/failures.txt"; fi; }')
    ad("")
    ad(f'stop_server () {{ PORT={port} "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }}')
    ad('trap stop_server EXIT')
    ad("")

    for srv in spec["servers"]:
        pslugs = [p["slug"] for p in srv["probes"]]
        ad(f'# ===== server: {srv["name"]} (ctx={srv["ctx"]} np={srv["np"]} '
           f'kv={srv["kv"]} mtp={srv["mtp"]}) =====')
        ad(f'if server_needed {" ".join(sh_quote(s) for s in pslugs)}; then')
        ad(f'  echo ">>> starting {srv["name"]}"')
        ad(f'  BACKEND={backend} CTX={srv["ctx"]} NP={srv["np"]} KV={srv["kv"]} '
           f'MTP={srv["mtp"]} UB={ub} B={b} FA={fa} PORT={port} \\')
        ad(f'    "$EB/serve_llamacpp.sh" start || {{ echo "server {srv["name"]} failed to start"; '
           f'stop_server; exit 1; }}')
        for p in srv["probes"]:
            files = " ".join(sh_quote(f) for f in p["prompts"])
            ad('  run_probe {slug} {conc} {reps} {maxt} {api} {prefix} {files}'.format(
                slug=sh_quote(p["slug"]), conc=p.get("concurrency", 1),
                reps=p.get("reps", 2), maxt=p.get("max_tokens", 256),
                api=p.get("api", "completions"), prefix=p.get("prefix_mode", "unique"),
                files=files))
        ad('  stop_server')
        ad('fi')
        ad("")

    ad('# ===== report (last step) =====')
    ad('if [ -f "$CAMPAIGN_DIR/results.jsonl" ]; then')
    ad('  python3 "$ROOT/bench/lib/report.py" "$CAMPAIGN_DIR" \\')
    ad('    && echo "report: $CAMPAIGN_DIR/report.html"')
    ad('fi')
    ad('echo "campaign done. consolidated results: $CAMPAIGN_DIR/results.jsonl"')
    return "\n".join(L) + "\n"


def emit_readme(spec):
    slug = spec["slug"]
    date = spec.get("date") or datetime.date.today().isoformat()
    title = spec.get("title", f"{slug} campaign")
    rows = []
    for srv in spec["servers"]:
        for p in srv["probes"]:
            rows.append(f"| {srv['name']} | {srv['ctx']} | {srv['np']} | {srv['kv']} | "
                        f"{srv['mtp']} | `{p['slug']}` | {p.get('concurrency',1)} | "
                        f"{', '.join(p['prompts'])} |")
    tune = spec.get("tuning", {})
    return f"""# {title} (R9700, {date})

Scaffolded by `bench/gen_campaign.py`. The executable driver is **`run.sh`** in this folder
(resumable — per-probe markers in `done/`, rerun to continue). Fill in the prose below.

## Fixed parameters
- Model `{os.path.basename(spec['model'])}` · backend **{spec.get('backend','vulkan')}** ·
  tuning `-ub {tune.get('ub',2048)} -b {tune.get('b',4096)} -fa {tune.get('fa','on')}` ·
  server on :{spec.get('port', BACKEND_PORT.get(spec.get('backend','vulkan'),8080))}.

## Build fixtures first
Build every prompt file referenced below into `bench/workloads/generated/` with
`build_prompt.py` (see `docs/GUIDE.md` §2). The driver assumes they exist.

## Run
```bash
bash docs/campaigns/{date}-{slug}/run.sh
# resume after interruption: same command (done/ markers skip finished probes)
```

## Matrix
| server | ctx | np | kv | mtp | probe | conc | prompts |
|--------|----:|---:|:--:|:---:|-------|-----:|---------|
{chr(10).join(rows)}

## Write-up
`/benchmark` → `docs/analysis/<stamp>-{slug}.md`; `report.html` auto-generated by `run.sh`'s last
step (`bench/lib/report.py`). Add a `<!-- meta -->` block to the report and run `docs/reindex.py`.
"""


def cmd_emit(args):
    with open(args.spec, encoding="utf-8") as fh:
        spec = json.load(fh)
    for k in ("slug", "model", "servers"):
        if k not in spec:
            sys.exit(f"spec missing required key: {k}")
    slugs = [p["slug"] for s in spec["servers"] for p in s["probes"]]
    if len(slugs) != len(set(slugs)):
        sys.exit("probe slugs must be unique across the campaign")
    date = spec.get("date") or datetime.date.today().isoformat()
    cdir = os.path.join(REPO, "docs", "campaigns", f"{date}-{spec['slug']}")
    run_sh = emit_runsh(spec)
    if args.print:
        sys.stdout.write(run_sh)
        return
    os.makedirs(cdir, exist_ok=True)
    run_path = os.path.join(cdir, "run.sh")
    with open(run_path, "w", encoding="utf-8") as fh:
        fh.write(run_sh)
    os.chmod(run_path, os.stat(run_path).st_mode | stat.S_IEXEC | stat.S_IXGRP)
    print(f"wrote {os.path.relpath(run_path, REPO)}")
    readme = os.path.join(cdir, "README.md")
    if os.path.exists(readme) and not args.force:
        print(f"kept existing {os.path.relpath(readme, REPO)} (use --force to overwrite)")
    else:
        with open(readme, "w", encoding="utf-8") as fh:
            fh.write(emit_readme(spec))
        print(f"wrote {os.path.relpath(readme, REPO)}")


def cmd_vram(args):
    base_mib = args.weights_gib * 1024 + args.overhead_mib
    kv_per_tok_mib = args.kv_kib_per_tok / 1024.0
    avail = args.budget_mib - base_mib
    if avail <= 0:
        sys.exit(f"budget {args.budget_mib} MiB < base {base_mib:.0f} MiB — weights don't fit")
    max_ctx = int(avail / kv_per_tok_mib)
    print(f"weights+overhead base : {base_mib:8.0f} MiB")
    print(f"f16 KV per token      : {args.kv_kib_per_tok:8.1f} KiB")
    print(f"budget                : {args.budget_mib:8.0f} MiB")
    print(f"-> max KV tokens (total, -c): {max_ctx:,}")
    if args.np > 1:
        print(f"-> per slot at -np {args.np}      : {max_ctx // args.np:,}")
    print("note: also capped by the model's native context (RoPE) — take the min.")


EXAMPLE = {
    "slug": "example", "model": "/home/dev/models/gguf/Model-Q4_K_M.gguf",
    "backend": "vulkan", "port": 8081, "tuning": {"ub": 2048, "b": 4096, "fa": "on"},
    "servers": [{
        "name": "single-mtp1", "ctx": 65536, "np": 1, "kv": "f16", "mtp": 1,
        "probes": [
            {"slug": "ex-cr8000", "prompts": ["codereview-8000.txt"],
             "max_tokens": 256, "api": "completions", "concurrency": 1, "reps": 2},
            {"slug": "ex-think", "prompts": ["thinking-hard.txt"],
             "max_tokens": 1024, "api": "chat", "concurrency": 1, "reps": 2},
        ]}]}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    e = sub.add_parser("emit", help="spec.json -> campaign dir (run.sh + README skeleton)")
    e.add_argument("--spec", required=True)
    e.add_argument("--force", action="store_true", help="overwrite an existing README.md")
    e.add_argument("--print", action="store_true", help="print run.sh to stdout, write nothing")
    e.set_defaults(func=cmd_emit)
    v = sub.add_parser("vram-ctx", help="VRAM budget -> max context tokens")
    v.add_argument("--weights-gib", type=float, required=True)
    v.add_argument("--kv-kib-per-tok", type=float, required=True,
                   help="measured f16 KV per token (e.g. 21 for Qwen3.6-35B-A3B)")
    v.add_argument("--budget-mib", type=float, required=True)
    v.add_argument("--overhead-mib", type=float, default=700.0,
                   help="non-KV runtime/compute buffers (default 700)")
    v.add_argument("--np", type=int, default=1)
    v.set_defaults(func=cmd_vram)
    x = sub.add_parser("example", help="print a minimal example spec")
    x.set_defaults(func=lambda _a: print(json.dumps(EXAMPLE, indent=2)))
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
