#!/usr/bin/env bash
# GENERATED by bench/gen_campaign.py — campaign 'deep-context'. Resumable: rerun to continue
# after an interruption (per-probe markers in <campaign>/done/). Edit the spec and
# regenerate, or hand-edit this file. Requires the servers' llama.cpp builds present.
set -uo pipefail
ROOT="${ROOT:-/home/dev/work/dp-craft/amd}"
CAMPAIGN_DIR="${CAMPAIGN_DIR:-$ROOT/bench/runs/2026-07-11-deep-context}"
EB="$ROOT/bench/engine-bench"
GEN="$ROOT/bench/workloads/generated"
export MODEL='/home/dev/models/gguf/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf'
export ENGINES_LIST="llamacpp-vulkan|http://localhost:8081/v1|local"
mkdir -p "$CAMPAIGN_DIR/done"
if [ ! -f "$CAMPAIGN_DIR/meta.txt" ]; then
  { echo "date=$(date -Iseconds)"; echo "model=$MODEL"; echo "backend=vulkan"; echo "tuning=ub2048 b4096 faon"; } > "$CAMPAIGN_DIR/meta.txt"
fi

server_needed () {  # any listed probe marker missing?
  local s; for s in "$@"; do [ -f "$CAMPAIGN_DIR/done/$s" ] || return 0; done; return 1; }

run_probe () {  # slug conc reps max_tokens api prefix prompt_files...
  local slug=$1 conc=$2 reps=$3 maxt=$4 api=$5 prefix=$6; shift 6
  if [ -f "$CAMPAIGN_DIR/done/$slug" ]; then echo "  skip (done): $slug"; return 0; fi
  local files=""; local f; for f in "$@"; do files="$files $GEN/$f"; done
  if PROMPT_FILE="$files" SLUG="$slug" MAX_TOKENS="$maxt" CONCURRENCY="$conc" \
       REPS="$reps" API="$api" PREFIX_MODE="$prefix" "$EB/run.sh"; then
    local rd; rd=$(ls -td "$ROOT"/bench/runs/*-engine-"$slug"/ 2>/dev/null | head -1)
    [ -n "$rd" ] && [ -f "$rd/results.jsonl" ] \
      && cat "$rd/results.jsonl" >> "$CAMPAIGN_DIR/results.jsonl"
    touch "$CAMPAIGN_DIR/done/$slug"
  else echo "  FAILED: $slug" | tee -a "$CAMPAIGN_DIR/failures.txt"; fi; }

stop_server () { PORT=8081 "$EB/serve_llamacpp.sh" stop 2>/dev/null || true; }
trap stop_server EXIT

# ===== server: single-mtp0 (ctx=262144 np=1 kv=f16 mtp=0) =====
if server_needed 'deep-mtp0-cr8000' 'deep-mtp0-cr128000' 'deep-mtp0-cr200000' 'deep-mtp0-think'; then
  echo ">>> starting single-mtp0"
  BACKEND=vulkan CTX=262144 NP=1 KV=f16 MTP=0 UB=2048 B=4096 FA=on PORT=8081 \
    "$EB/serve_llamacpp.sh" start || { echo "server single-mtp0 failed to start"; stop_server; exit 1; }
  run_probe 'deep-mtp0-cr8000' 1 2 256 completions unique 'codereview-8000.txt'
  run_probe 'deep-mtp0-cr128000' 1 2 256 completions unique 'codereview-128000.txt'
  run_probe 'deep-mtp0-cr200000' 1 2 256 completions unique 'codereview-200000.txt'
  run_probe 'deep-mtp0-think' 1 2 1024 chat unique 'thinking-hard.txt'
  stop_server
fi

# ===== server: single-mtp1 (ctx=262144 np=1 kv=f16 mtp=1) =====
if server_needed 'deep-mtp1-cr8000' 'deep-mtp1-cr128000' 'deep-mtp1-cr200000' 'deep-mtp1-think'; then
  echo ">>> starting single-mtp1"
  BACKEND=vulkan CTX=262144 NP=1 KV=f16 MTP=1 UB=2048 B=4096 FA=on PORT=8081 \
    "$EB/serve_llamacpp.sh" start || { echo "server single-mtp1 failed to start"; stop_server; exit 1; }
  run_probe 'deep-mtp1-cr8000' 1 2 256 completions unique 'codereview-8000.txt'
  run_probe 'deep-mtp1-cr128000' 1 2 256 completions unique 'codereview-128000.txt'
  run_probe 'deep-mtp1-cr200000' 1 2 256 completions unique 'codereview-200000.txt'
  run_probe 'deep-mtp1-think' 1 2 1024 chat unique 'thinking-hard.txt'
  stop_server
fi

# ===== server: single-mtp1-q8 (ctx=262144 np=1 kv=q8_0 mtp=1) =====
if server_needed 'deep-mtp1q8-cr200000'; then
  echo ">>> starting single-mtp1-q8"
  BACKEND=vulkan CTX=262144 NP=1 KV=q8_0 MTP=1 UB=2048 B=4096 FA=on PORT=8081 \
    "$EB/serve_llamacpp.sh" start || { echo "server single-mtp1-q8 failed to start"; stop_server; exit 1; }
  run_probe 'deep-mtp1q8-cr200000' 1 2 256 completions unique 'codereview-200000.txt'
  stop_server
fi

# ===== server: parallel-np2 (ctx=262144 np=2 kv=f16 mtp=0) =====
if server_needed 'deep-par-np2'; then
  echo ">>> starting parallel-np2"
  BACKEND=vulkan CTX=262144 NP=2 KV=f16 MTP=0 UB=2048 B=4096 FA=on PORT=8081 \
    "$EB/serve_llamacpp.sh" start || { echo "server parallel-np2 failed to start"; stop_server; exit 1; }
  run_probe 'deep-par-np2' 2 2 256 completions unique 'agentic-32000-v1.txt' 'agentic-32000-v2.txt'
  stop_server
fi

# ===== server: parallel-np4 (ctx=262144 np=4 kv=f16 mtp=0) =====
if server_needed 'deep-par-np4'; then
  echo ">>> starting parallel-np4"
  BACKEND=vulkan CTX=262144 NP=4 KV=f16 MTP=0 UB=2048 B=4096 FA=on PORT=8081 \
    "$EB/serve_llamacpp.sh" start || { echo "server parallel-np4 failed to start"; stop_server; exit 1; }
  run_probe 'deep-par-np4' 4 2 256 completions unique 'agentic-32000-v1.txt' 'agentic-32000-v2.txt' 'agentic-32000-v3.txt' 'agentic-32000-v4.txt'
  stop_server
fi

# ===== report (last step) =====
if [ -f "$CAMPAIGN_DIR/results.jsonl" ]; then
  python3 "$ROOT/bench/lib/report.py" "$CAMPAIGN_DIR" \
    && echo "report: $CAMPAIGN_DIR/report.html"
fi
echo "campaign done. consolidated results: $CAMPAIGN_DIR/results.jsonl"
